query UserInfo ($login: String!) { 
  user(login: $login) {
    id
    name
    avatarUrl
    bio
  }
}

query Credentials {
  viewer {
    id
    login
  }
}

mutation FollowUser($id: ID!, $clientMutationId: String) {
  followUser(input: {userId: $id, clientMutationId: $clientMutationId}) {
    clientMutationId
  }
}

mutation UnfollowUser($id: ID!, $clientMutationId: String) {
  unfollowUser(input: {userId: $id, clientMutationId: $clientMutationId}) {
    clientMutationId
  }
}