/** @generated THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Types from '../../../shared/api/models.gen';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type OrgPinnedQueryVariables = Types.Exact<{
  login: Types.Scalars['String'];
}>;


export type OrgPinnedQuery = { readonly organization?: Types.Maybe<{ readonly pinnedItems: { readonly nodes?: Types.Maybe<ReadonlyArray<Types.Maybe<{ readonly id: string, readonly name: string, readonly updatedAt: any, readonly viewerHasStarred: boolean, readonly primaryLanguage?: Types.Maybe<{ readonly color?: Types.Maybe<string>, readonly name: string }>, readonly owner: { readonly login: string } | { readonly login: string } }>>> } }> };


export const OrgPinnedDocument = gql`
    query OrgPinned($login: String!) {
  organization(login: $login) {
    pinnedItems(first: 3) {
      nodes {
        ... on Repository {
          id
          name
          primaryLanguage {
            color
            name
          }
          owner {
            login
          }
          updatedAt
          viewerHasStarred
        }
      }
    }
  }
}
    `;

/**
 * __useOrgPinnedQuery__
 *
 * To run a query within a React component, call `useOrgPinnedQuery` and pass it any options that fit your needs.
 * When your component renders, `useOrgPinnedQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOrgPinnedQuery({
 *   variables: {
 *      login: // value for 'login'
 *   },
 * });
 */
export function useOrgPinnedQuery(baseOptions?: Apollo.QueryHookOptions<OrgPinnedQuery, OrgPinnedQueryVariables>) {
        return Apollo.useQuery<OrgPinnedQuery, OrgPinnedQueryVariables>(OrgPinnedDocument, baseOptions);
      }
export function useOrgPinnedLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<OrgPinnedQuery, OrgPinnedQueryVariables>) {
          return Apollo.useLazyQuery<OrgPinnedQuery, OrgPinnedQueryVariables>(OrgPinnedDocument, baseOptions);
        }
export type OrgPinnedQueryHookResult = ReturnType<typeof useOrgPinnedQuery>;
export type OrgPinnedLazyQueryHookResult = ReturnType<typeof useOrgPinnedLazyQuery>;
export type OrgPinnedQueryResult = Apollo.QueryResult<OrgPinnedQuery, OrgPinnedQueryVariables>;