query RepoDefaultBranch($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    id
    defaultBranchRef {
      name
    }
  }
}


query RepoBranchInfo($owner: String!, $name: String!, $qualifiedName: String!, $expression: String!, $readmeLower: String!, $readmeUpper: String!) {
  repository(owner: $owner, name: $name) {
    id
    url
    ref(qualifiedName: $qualifiedName) {
      name
      target {
        ... on Commit {
          id
          messageHeadline
          author {
            date
            name
            user {
              avatarUrl(size: 36)
              login
            }
          }
        }
      }
    }
    object(expression: $expression) {
      ... on Tree {
        entries {
          name
          extension
          type
        }
      }
    }
    contentLower: object(expression: $readmeLower) {
      ... on Blob {
        text
      }
    }
    contentUpper: object(expression: $readmeUpper) {
      ... on Blob {
        text
      }
    }
    refs(first: 20, refPrefix: "refs/heads/", orderBy: {field: ALPHABETICAL, direction: ASC}) {
      nodes {
        name
        prefix
      }
    }
  }
}
