fragment RepositoriesDetails on RepositoryConnection {
  	pageInfo {
        endCursor
        startCursor
        hasNextPage
        hasPreviousPage
      }
      totalCount
      nodes {
        id
        name
        primaryLanguage {
          color
          name
        }
        owner {
          login
        }
        updatedAt
        viewerHasStarred
      }
}

query Repos ($login: String!, $ownerAffiliations: [RepositoryAffiliation], $after: String, $before: String, $first: Int, $last: Int) { 
  user(login: $login) {
    id
    repositories(ownerAffiliations: $ownerAffiliations, orderBy: {field: PUSHED_AT, direction: DESC}, after: $after, before: $before, first: $first, last: $last) {
      ...RepositoriesDetails
    } 
  }
}
