/** @generated THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Types from '../../../shared/api/models.gen';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type OrgDetailsQueryVariables = Types.Exact<{
  login: Types.Scalars['String'];
}>;


export type OrgDetailsQuery = { readonly organization?: Types.Maybe<{ readonly name?: Types.Maybe<string>, readonly description?: Types.Maybe<string>, readonly location?: Types.Maybe<string>, readonly email?: Types.Maybe<string>, readonly avatarUrl: any, readonly twitterUsername?: Types.Maybe<string> }> };


export const OrgDetailsDocument = gql`
    query OrgDetails($login: String!) {
  organization(login: $login) {
    name
    description
    location
    email
    avatarUrl
    twitterUsername
  }
}
    `;

/**
 * __useOrgDetailsQuery__
 *
 * To run a query within a React component, call `useOrgDetailsQuery` and pass it any options that fit your needs.
 * When your component renders, `useOrgDetailsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOrgDetailsQuery({
 *   variables: {
 *      login: // value for 'login'
 *   },
 * });
 */
export function useOrgDetailsQuery(baseOptions?: Apollo.QueryHookOptions<OrgDetailsQuery, OrgDetailsQueryVariables>) {
        return Apollo.useQuery<OrgDetailsQuery, OrgDetailsQueryVariables>(OrgDetailsDocument, baseOptions);
      }
export function useOrgDetailsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<OrgDetailsQuery, OrgDetailsQueryVariables>) {
          return Apollo.useLazyQuery<OrgDetailsQuery, OrgDetailsQueryVariables>(OrgDetailsDocument, baseOptions);
        }
export type OrgDetailsQueryHookResult = ReturnType<typeof useOrgDetailsQuery>;
export type OrgDetailsLazyQueryHookResult = ReturnType<typeof useOrgDetailsLazyQuery>;
export type OrgDetailsQueryResult = Apollo.QueryResult<OrgDetailsQuery, OrgDetailsQueryVariables>;