query RepositoryGitInfo($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
        object(expression: "master:") {
            ... on Tree {
                entries {
                    name
                    type
                    extension
                }
            }
        }

        ref(qualifiedName: "master") {
            target {
                ... on Commit {
                    id
                    history(first: 1) {
                        edges {
                            node {
                                messageHeadline
                                oid
                                message
                                author {
                                    name
                                    email
                                    date
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
