query OrgRepoList ($login: String!)  {
  organization(login: $login) {
    id
    repositories(first: 10) {
      nodes {
        id
        name
        primaryLanguage {
            color
            name
        }
        owner {
            login
        }
        updatedAt
        viewerHasStarred
        }
    }
  }
}
