query Repos ($login: String!, $ownerAffiliations: [RepositoryAffiliation]) { 
  user(login: $login) {
    repositories(ownerAffiliations: $ownerAffiliations, first: 50, orderBy: {field: PUSHED_AT, direction: DESC}) {
      edges {
        node {
          id
          name
          primaryLanguage {
            color
            name
          }
          updatedAt
          viewerHasStarred
          url
        }
      }
    } 
  }
}